name: Update README with APOD

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Update Script
        run: node scripts/update-readme.js
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update APOD: $(date +'%Y-%m-%d')" || exit 0
          git push